language: python
python:
  - "3.6"  # current default Python on Travis CI
  - "3.7"
  - "3.8"
# install codecov
install:
  - pip3 install codecov
  - pip3 install coverage
# command to run tests
script:
  - python3 -m unittest
  - coverage run -m unittest discover
# build coverage
after-success:
  - codecov
